services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password
      REDIS_PORT : 6379
      REDIS_DATABASES: 16
  mongo:
    container_name: mongodb
    image: mongo
    build: 
      context: ./db/mongodb_rs
      args:
        MONGO_VERSION: latest
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: oncepal
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - 27017:27017